/**
 * Harbour Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection.
 *
 * Why this file exists:
 *   OpenNext on Cloudflare Workers does NOT honour `next.config.ts`
 *   `headers()`. We therefore:
 *     1. import OpenNext's default fetch handler from .open-next/worker.js
 *     2. re-export the Durable Object classes verbatim (wrangler binds
 *        them by class name; missing exports = deploy fails)
 *     3. export a default whose `fetch` overlays security headers on
 *        every response.
 *
 * Background: see `docs/security/cf-headers-wrapper.md`.
 */

// The .open-next/worker.js module is generated by
// `npx opennextjs-cloudflare build` and is gitignored. After a fresh
// clone you must run that build before running tsc in this app — the
// build command runs as part of the deploy pipeline, so this is only a
// concern for local dev.
//
// Use @ts-ignore (not @ts-expect-error) so the directive is silently
// no-op when .open-next is present (post-build) and silences the import
// error when it isn't (fresh clone).
//
// @ts-ignore
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  HARBOUR_DEFAULT_CSP,
} from "@windedvertigo/security";

// Re-export Durable Object classes so wrangler's bundler keeps them in
// the deployed worker. Without these, the worker fails at runtime when
// OpenNext tries to instantiate the queue / sharded-tag-cache /
// bucket-cache-purge DOs declared in wrangler.jsonc bindings.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

// The default export is a fetch handler that:
//   - delegates to OpenNext's handler for the actual request
//   - overlays the 5 standard security headers on the response
//   - injects the harbour CSP if the inner response didn't set its own
export default wrapWithSecurityHeaders(openNextHandler, {
  csp: HARBOUR_DEFAULT_CSP,
  // Bypass injection on Cloudflare's image pipeline internal paths.
  // Static assets bound at `assets.binding = "ASSETS"` are served by the
  // runtime BEFORE worker code runs, so they don't reach this handler at
  // all — this skip is belt-and-braces for cdn-cgi paths only.
  skipPaths: [/^\/cdn-cgi\//],
});
