/**
 * Rubric Co-Builder Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection.
 *
 * OpenNext on CF Workers does NOT honour next.config.ts headers(); we wrap
 * the fetch handler with wrapWithSecurityHeaders. No crons, no Auth.js,
 * no Durable Objects — simpler than creaseworks/worker.ts.
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`; absent on fresh clone.
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  HARBOUR_DEFAULT_CSP,
} from "@windedvertigo/security";

// Re-export Durable Object classes so wrangler keeps them in the deployed
// worker. Without these, OpenNext's queue / tag-cache DOs fail at runtime.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

export default {
  fetch: wrapWithSecurityHeaders(openNextHandler, {
    csp: HARBOUR_DEFAULT_CSP,
    skipPaths: [/^\/cdn-cgi\//],
  }).fetch,
};
