'use client';

/**
 * /pcs/canonical-claims/backfill-review — Phase 4.6 Bundle B.3
 *
 * Side-by-side review of PCS Claim → Canonical Claim mapping proposals
 * generated by the regex matcher (lib/canonical-claim-matcher.js).
 *
 * Lauren / RES / RA see each PCS claim's free-text title (left column)
 * alongside the proposed canonical / prefix / benefit / wording variants
 * (right column). Approve writes the relations to Notion in one call.
 *
 * Flagging via the existing Wave 6.1 Feedback Button (mounted on every
 * PCS page) — operators leave notes about misclassifications.
 *
 * Status filters at top of page:
 *   - Pending (high)   — confidence ≥ 0.7, not yet linked
 *   - Pending (low)    — confidence < 0.7 with a candidate match
 *   - Unmatchable      — no canonical match found
 *   - Applied          — already linked (read-only audit view)
 */

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/lib/useAuth';
import { hasAnyRole, ROLE_SETS } from '@/lib/auth/has-any-role';

const STATUS_OPTIONS = [
  { value: 'pending-high', label: 'Pending (high confidence)', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { value: 'pending-low',  label: 'Pending (low)',             color: 'bg-orange-100 text-orange-900 border-orange-300' },
  { value: 'unmatchable',  label: 'Unmatchable',                color: 'bg-gray-100 text-gray-700 border-gray-300' },
  { value: 'applied',      label: 'Applied',                    color: 'bg-green-100 text-green-900 border-green-300' },
];

export default function BackfillReviewPage() {
  const { user } = useAuth();
  const canEdit = hasAnyRole(user, ROLE_SETS.PCS_WRITERS);

  const [proposals, setProposals] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [status, setStatus] = useState('pending-high');
  const [approving, setApproving] = useState({});
  const [approvalLog, setApprovalLog] = useState({});

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/pcs/canonical-claims/backfill-review?status=${status}`);
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `HTTP ${res.status}`);
      }
      const data = await res.json();
      setProposals(data.proposals || []);
      setStats(data.stats || null);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status]);

  const onApprove = async (p, opts = {}) => {
    setApproving((s) => ({ ...s, [p.pcsClaimId]: true }));
    try {
      const res = await fetch('/api/pcs/canonical-claims/backfill-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          pcsClaimId: p.pcsClaimId,
          canonicalClaimId: opts.canonicalId !== undefined ? opts.canonicalId : p.proposedCanonical?.id || null,
          claimPrefixId: opts.prefixId !== undefined ? opts.prefixId : p.proposedPrefix?.id || null,
          coreBenefitIds: opts.benefitIds !== undefined ? opts.benefitIds : (p.proposedBenefits?.map((b) => b.id) || []),
          variants: opts.variants !== undefined ? opts.variants : p.variants,
        }),
      });
      const body = await res.json();
      if (!res.ok) throw new Error(body.error || `HTTP ${res.status}`);
      setApprovalLog((s) => ({ ...s, [p.pcsClaimId]: { ok: true, variantsCreated: body.variantsCreated } }));
      // Optimistic: mark applied locally and remove from list (refresh next change)
      setProposals((prev) => prev.filter((x) => x.pcsClaimId !== p.pcsClaimId));
    } catch (err) {
      setApprovalLog((s) => ({ ...s, [p.pcsClaimId]: { ok: false, message: err.message } }));
    } finally {
      setApproving((s) => ({ ...s, [p.pcsClaimId]: false }));
    }
  };

  const visible = useMemo(() => proposals, [proposals]);

  return (
    <div className="space-y-6">
      <div>
        <div className="text-xs text-gray-500 mb-1">PCS · Canonical Claims</div>
        <h1 className="text-2xl font-bold text-gray-900">Backfill Review Queue</h1>
        <p className="text-sm text-gray-600 mt-1 max-w-3xl">
          Review the regex-heuristic proposals for linking each free-text PCS claim to its canonical
          form, claim prefix, and core benefit. Approve writes the relations and creates Wording Variant
          rows. Flag misclassifications via the feedback button (bottom-right).
        </p>
      </div>

      {/* Stats */}
      {stats ? (
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          <Stat label="Total PCS Claims" value={stats.total} />
          <Stat label="Applied" value={stats.applied} className="text-green-700" />
          <Stat label="Pending (high)" value={stats.pendingHigh} className="text-amber-700" />
          <Stat label="Pending (low)" value={stats.pendingLow} className="text-orange-700" />
          <Stat label="Unmatchable" value={stats.unmatchable} className="text-gray-600" />
        </div>
      ) : null}

      {/* Status filter chips */}
      <div className="flex flex-wrap gap-2">
        {STATUS_OPTIONS.map((s) => (
          <button
            key={s.value}
            onClick={() => setStatus(s.value)}
            className={`px-3 py-1 rounded-full text-xs font-medium transition border ${
              status === s.value ? s.color : 'bg-white text-gray-700 border-gray-200 hover:bg-gray-50'
            }`}
          >
            {s.label}
          </button>
        ))}
        <button
          onClick={load}
          className="ml-auto px-3 py-1 rounded-full text-xs font-medium bg-pacific-50 text-pacific-700 border border-pacific-200 hover:bg-pacific-100"
        >
          ⟳ Refresh
        </button>
      </div>

      {/* Body */}
      {loading ? (
        <div className="space-y-3 animate-pulse">
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="h-24 bg-gray-100 rounded-lg" />
          ))}
        </div>
      ) : error ? (
        <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-900">
          <p className="font-semibold mb-1">Failed to load proposals</p>
          <p>{error}</p>
        </div>
      ) : visible.length === 0 ? (
        <div className="rounded-lg border border-gray-200 bg-white p-10 text-center text-gray-600">
          No proposals in this filter. Pick another status above.
        </div>
      ) : (
        <div className="space-y-3">
          {visible.map((p) => (
            <ProposalRow
              key={p.pcsClaimId}
              p={p}
              canEdit={canEdit}
              busy={!!approving[p.pcsClaimId]}
              feedback={approvalLog[p.pcsClaimId]}
              onApprove={onApprove}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function Stat({ label, value, className = '' }) {
  return (
    <div className="rounded-lg border border-gray-200 bg-white p-3">
      <div className="text-xs text-gray-500">{label}</div>
      <div className={`text-2xl font-bold ${className || 'text-gray-900'}`}>{value ?? '—'}</div>
    </div>
  );
}

function ConfidenceBadge({ score }) {
  const color =
    score >= 0.99 ? 'bg-green-100 text-green-800 border-green-300' :
    score >= 0.7  ? 'bg-amber-100 text-amber-800 border-amber-300' :
    score >= 0.5  ? 'bg-orange-100 text-orange-800 border-orange-300' :
                    'bg-gray-100 text-gray-700 border-gray-300';
  return (
    <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium border ${color}`}>
      {score.toFixed(2)}
    </span>
  );
}

function ProposalRow({ p, canEdit, busy, feedback, onApprove }) {
  const isApplied = !!p.currentCanonicalId;
  return (
    <div className="rounded-lg border border-gray-200 bg-white p-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* LEFT — original */}
        <div className="space-y-2">
          <div className="text-[11px] uppercase tracking-wide text-gray-500">Original PCS claim</div>
          <div className="text-sm text-gray-900 font-medium leading-snug">{p.pcsClaimTitle}</div>
          <div className="text-[11px] text-gray-400 font-mono">{p.pcsClaimId.slice(0, 8)}…</div>
        </div>

        {/* RIGHT — proposed */}
        <div className="space-y-2 border-l border-gray-100 md:pl-4">
          <div className="flex items-center justify-between">
            <div className="text-[11px] uppercase tracking-wide text-gray-500">Proposed mapping</div>
            <ConfidenceBadge score={p.confidence} />
          </div>

          <Field label="Canonical Claim" value={p.proposedCanonical ? `${p.proposedCanonical.title} (${p.proposedCanonical.score.toFixed(2)})` : '—'} />
          <Field label="Claim Prefix" value={p.proposedPrefix?.title || '—'} />
          <Field
            label="Core Benefit(s)"
            value={p.proposedBenefits.length > 0 ? p.proposedBenefits.map((b) => `${b.title} (${b.score.toFixed(2)})`).join(', ') : '—'}
          />
          {p.variants && p.variants.length > 1 ? (
            <div className="text-xs text-gray-700">
              <span className="text-[10px] uppercase tracking-wide text-gray-500">Variants ({p.variants.length}): </span>
              <span className="italic">{p.variants[0]} · …</span>
            </div>
          ) : null}
        </div>
      </div>

      {/* Action row */}
      <div className="flex items-center gap-3 mt-3 pt-3 border-t border-gray-100">
        {isApplied ? (
          <span className="text-xs px-2 py-1 rounded bg-green-50 text-green-800">
            ✓ Applied (current canonical: {p.currentCanonicalId.slice(0, 8)}…)
          </span>
        ) : (
          <>
            <button
              type="button"
              disabled={!canEdit || busy || !p.proposedCanonical}
              onClick={() => onApprove(p)}
              className={`px-3 py-1 rounded text-xs font-medium border ${
                canEdit && p.proposedCanonical
                  ? 'bg-pacific-600 text-white border-pacific-600 hover:bg-pacific-700 disabled:opacity-50'
                  : 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed'
              }`}
            >
              {busy ? 'Approving…' : '✓ Approve as proposed'}
            </button>
            {p.proposedCanonical ? (
              <Link
                href={`/research/pcs/canonical-claims/${p.proposedCanonical.id}`}
                className="text-xs text-pacific-600 hover:underline"
                target="_blank"
              >
                Open canonical →
              </Link>
            ) : null}
            <Link
              href={`/research/pcs/claims/${p.pcsClaimId}`}
              className="text-xs text-gray-600 hover:underline"
              target="_blank"
            >
              Open PCS claim →
            </Link>
          </>
        )}
        {feedback ? (
          <span className={`ml-auto text-xs ${feedback.ok ? 'text-green-700' : 'text-red-700'}`}>
            {feedback.ok ? `✓ ${feedback.variantsCreated || 0} variant(s) created` : `✗ ${feedback.message}`}
          </span>
        ) : null}
      </div>
    </div>
  );
}

function Field({ label, value }) {
  return (
    <div className="text-xs text-gray-700">
      <span className="text-[10px] uppercase tracking-wide text-gray-500">{label}: </span>
      <span>{value}</span>
    </div>
  );
}
