'use client';

/**
 * /pcs/canonical-claims/backfill-review — Phase 4.6 Bundle B.3
 *
 * Side-by-side review of PCS Claim → Canonical Claim mapping proposals
 * generated by the regex matcher (lib/canonical-claim-matcher.js).
 *
 * Lauren / RES / RA see each PCS claim's free-text title (left column)
 * alongside the proposed canonical / prefix / benefit / wording variants
 * (right column). Approve writes the relations to Notion in one call.
 *
 * Flagging via the existing Wave 6.1 Feedback Button (mounted on every
 * PCS page) — operators leave notes about misclassifications.
 *
 * Status filters at top of page:
 *   - Pending (high)   — confidence ≥ 0.7, not yet linked
 *   - Pending (low)    — confidence < 0.7 with a candidate match
 *   - Unmatchable      — no canonical match found
 *   - Applied          — already linked (read-only audit view)
 */

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/lib/useAuth';
import { hasAnyRole, ROLE_SETS } from '@/lib/auth/has-any-role';

const STATUS_OPTIONS = [
  { value: 'pending-high', label: 'Pending (high confidence)', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { value: 'pending-low',  label: 'Pending (low)',             color: 'bg-orange-100 text-orange-900 border-orange-300' },
  { value: 'unmatchable',  label: 'Unmatchable',                color: 'bg-gray-100 text-gray-700 border-gray-300' },
  { value: 'applied',      label: 'Applied',                    color: 'bg-green-100 text-green-900 border-green-300' },
];

export default function BackfillReviewPage() {
  const { user } = useAuth();
  const canEdit = hasAnyRole(user, ROLE_SETS.PCS_WRITERS);

  const [proposals, setProposals] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [status, setStatus] = useState('pending-high');
  const [approving, setApproving] = useState({});
  const [approvalLog, setApprovalLog] = useState({});
  const [allCanonicals, setAllCanonicals] = useState([]);
  const [allPrefixes, setAllPrefixes] = useState([]);

  // Load all canonical claims + prefixes once so ProposalRow can offer override pickers.
  useEffect(() => {
    fetch('/api/pcs/canonical-claims')
      .then(r => r.ok ? r.json() : [])
      .then(data => setAllCanonicals(Array.isArray(data) ? data : []))
      .catch(() => {});
    fetch('/api/pcs/prefixes')
      .then(r => r.ok ? r.json() : [])
      .then(data => setAllPrefixes(Array.isArray(data) ? data : []))
      .catch(() => {});
  }, []);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/pcs/canonical-claims/backfill-review?status=${status}`);
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `HTTP ${res.status}`);
      }
      const data = await res.json();
      setProposals(data.proposals || []);
      setStats(data.stats || null);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status]);

  const onApprove = async (p, opts = {}) => {
    setApproving((s) => ({ ...s, [p.pcsClaimId]: true }));
    try {
      const res = await fetch('/api/pcs/canonical-claims/backfill-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          pcsClaimId: p.pcsClaimId,
          canonicalClaimId: opts.canonicalId !== undefined ? opts.canonicalId : p.proposedCanonical?.id || null,
          claimPrefixId: opts.prefixId !== undefined ? opts.prefixId : p.proposedPrefix?.id || null,
          coreBenefitIds: opts.benefitIds !== undefined ? opts.benefitIds : (p.proposedBenefits?.map((b) => b.id) || []),
          variants: opts.variants !== undefined ? opts.variants : p.variants,
        }),
      });
      const body = await res.json();
      if (!res.ok) throw new Error(body.error || `HTTP ${res.status}`);
      setApprovalLog((s) => ({ ...s, [p.pcsClaimId]: { ok: true, variantsCreated: body.variantsCreated } }));
      // Optimistic: mark applied locally and remove from list (refresh next change)
      setProposals((prev) => prev.filter((x) => x.pcsClaimId !== p.pcsClaimId));
    } catch (err) {
      setApprovalLog((s) => ({ ...s, [p.pcsClaimId]: { ok: false, message: err.message } }));
    } finally {
      setApproving((s) => ({ ...s, [p.pcsClaimId]: false }));
    }
  };

  const visible = useMemo(() => proposals, [proposals]);

  return (
    <div className="space-y-6">
      <div>
        <div className="text-xs text-gray-500 mb-1">PCS · Canonical Claims</div>
        <h1 className="text-2xl font-bold text-gray-900">Backfill Review Queue</h1>
        <p className="text-sm text-gray-600 mt-1 max-w-3xl">
          Review the regex-heuristic proposals for linking each free-text PCS claim to its canonical
          form, claim prefix, and core benefit. Approve writes the relations and creates Wording Variant
          rows. Flag misclassifications via the feedback button (bottom-right).
        </p>
      </div>

      {/* Stats */}
      {stats ? (
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          <Stat label="Total PCS Claims" value={stats.total} />
          <Stat label="Applied" value={stats.applied} className="text-green-700" />
          <Stat label="Pending (high)" value={stats.pendingHigh} className="text-amber-700" />
          <Stat label="Pending (low)" value={stats.pendingLow} className="text-orange-700" />
          <Stat label="Unmatchable" value={stats.unmatchable} className="text-gray-600" />
        </div>
      ) : null}

      {/* Status filter chips */}
      <div className="flex flex-wrap gap-2">
        {STATUS_OPTIONS.map((s) => (
          <button
            key={s.value}
            onClick={() => setStatus(s.value)}
            className={`px-3 py-1 rounded-full text-xs font-medium transition border ${
              status === s.value ? s.color : 'bg-white text-gray-700 border-gray-200 hover:bg-gray-50'
            }`}
          >
            {s.label}
          </button>
        ))}
        <button
          onClick={load}
          className="ml-auto px-3 py-1 rounded-full text-xs font-medium bg-pacific-50 text-pacific-700 border border-pacific-200 hover:bg-pacific-100"
        >
          ⟳ Refresh
        </button>
      </div>

      {/* Body */}
      {loading ? (
        <div className="space-y-3 animate-pulse">
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="h-24 bg-gray-100 rounded-lg" />
          ))}
        </div>
      ) : error ? (
        <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-900">
          <p className="font-semibold mb-1">Failed to load proposals</p>
          <p>{error}</p>
        </div>
      ) : visible.length === 0 ? (
        <div className="rounded-lg border border-gray-200 bg-white p-10 text-center text-gray-600">
          No proposals in this filter. Pick another status above.
        </div>
      ) : (
        <div className="space-y-3">
          {visible.map((p) => (
            <ProposalRow
              key={p.pcsClaimId}
              p={p}
              canEdit={canEdit}
              busy={!!approving[p.pcsClaimId]}
              feedback={approvalLog[p.pcsClaimId]}
              onApprove={onApprove}
              allCanonicals={allCanonicals}
              allPrefixes={allPrefixes}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function Stat({ label, value, className = '' }) {
  return (
    <div className="rounded-lg border border-gray-200 bg-white p-3">
      <div className="text-xs text-gray-500">{label}</div>
      <div className={`text-2xl font-bold ${className || 'text-gray-900'}`}>{value ?? '—'}</div>
    </div>
  );
}

function ConfidenceBadge({ score }) {
  const color =
    score >= 0.99 ? 'bg-green-100 text-green-800 border-green-300' :
    score >= 0.7  ? 'bg-amber-100 text-amber-800 border-amber-300' :
    score >= 0.5  ? 'bg-orange-100 text-orange-800 border-orange-300' :
                    'bg-gray-100 text-gray-700 border-gray-300';
  return (
    <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium border ${color}`}>
      {score.toFixed(2)}
    </span>
  );
}

function ProposalRow({ p, canEdit, busy, feedback, onApprove, allCanonicals, allPrefixes }) {
  const isApplied = !!p.currentCanonicalId;
  const [selectedId, setSelectedId] = useState(p.proposedCanonical?.id || '');
  const [selectedPrefixId, setSelectedPrefixId] = useState(p.proposedPrefix?.id || '');
  const isOverridden = (selectedId && selectedId !== (p.proposedCanonical?.id || ''))
    || (selectedPrefixId !== (p.proposedPrefix?.id || ''));

  // Sort canonicals: proposed first (if any), then alphabetical rest.
  // API objects use `canonicalClaim` for the text field (not `title`).
  const sortedCanonicals = useMemo(() => {
    const proposed = p.proposedCanonical ? allCanonicals.find(c => c.id === p.proposedCanonical.id) : null;
    const rest = allCanonicals
      .filter(c => !proposed || c.id !== proposed.id)
      .sort((a, b) => (a.canonicalClaim || a.title || '').localeCompare(b.canonicalClaim || b.title || ''));
    return proposed ? [proposed, ...rest] : rest;
  }, [allCanonicals, p.proposedCanonical]);

  return (
    <div className="rounded-lg border border-gray-200 bg-white p-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* LEFT — original PCS claim text (prominent for cross-checking) */}
        <div className="space-y-2">
          <div className="text-[11px] uppercase tracking-wide text-gray-500">PCS Claim Text</div>
          <div className="rounded-md bg-gray-50 border border-gray-200 px-3 py-2">
            <p className="text-sm text-gray-900 font-medium leading-snug">{p.pcsClaimTitle}</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-[11px] text-gray-400 font-mono">{p.pcsClaimId.slice(0, 8)}…</span>
            <Link href={`/research/pcs/claims/${p.pcsClaimId}`} className="text-[11px] text-pacific-600 hover:underline" target="_blank">
              Open claim →
            </Link>
          </div>
        </div>

        {/* RIGHT — canonical override picker */}
        <div className="space-y-3 border-l border-gray-100 md:pl-4">
          <div className="flex items-center justify-between">
            <div className="text-[11px] uppercase tracking-wide text-gray-500">Canonical mapping</div>
            <ConfidenceBadge score={p.confidence} />
          </div>

          {/* Canonical claim dropdown */}
          <div>
            <label className="text-[10px] uppercase tracking-wide text-gray-500 block mb-1">
              Canonical Claim
              {p.proposedCanonical && (
                <span className={`ml-2 text-[10px] font-normal ${isOverridden ? 'text-amber-600' : 'text-gray-400'}`}>
                  {isOverridden ? '(overridden)' : `auto-suggested · ${p.proposedCanonical.score.toFixed(2)}`}
                </span>
              )}
            </label>
            <select
              value={selectedId}
              onChange={e => setSelectedId(e.target.value)}
              disabled={!canEdit || isApplied}
              className="w-full text-xs border border-gray-300 rounded px-2 py-1.5 bg-white focus:ring-2 focus:ring-pacific-300 focus:border-transparent disabled:bg-gray-50 disabled:text-gray-500"
            >
              <option value="">— No canonical —</option>
              {p.proposedCanonical && (
                <optgroup label="Auto-suggested">
                  <option value={p.proposedCanonical.id}>
                    {p.proposedCanonical.title} ({p.proposedCanonical.score.toFixed(2)})
                  </option>
                </optgroup>
              )}
              {sortedCanonicals.filter(c => !p.proposedCanonical || c.id !== p.proposedCanonical.id).length > 0 && (
                <optgroup label="All canonicals">
                  {sortedCanonicals
                    .filter(c => !p.proposedCanonical || c.id !== p.proposedCanonical.id)
                    .map(c => (
                      <option key={c.id} value={c.id}>{c.canonicalClaim || c.title}</option>
                    ))}
                </optgroup>
              )}
            </select>
          </div>

          {/* Claim prefix dropdown */}
          <div>
            <label className="text-[10px] uppercase tracking-wide text-gray-500 block mb-1">
              Claim Prefix
              {p.proposedPrefix && (
                <span className={`ml-2 text-[10px] font-normal ${selectedPrefixId !== (p.proposedPrefix?.id || '') ? 'text-amber-600' : 'text-gray-400'}`}>
                  {selectedPrefixId !== (p.proposedPrefix?.id || '') ? '(overridden)' : 'auto-suggested'}
                </span>
              )}
            </label>
            <select
              value={selectedPrefixId}
              onChange={e => setSelectedPrefixId(e.target.value)}
              disabled={!canEdit || isApplied}
              className="w-full text-xs border border-gray-300 rounded px-2 py-1.5 bg-white focus:ring-2 focus:ring-pacific-300 focus:border-transparent disabled:bg-gray-50 disabled:text-gray-500"
            >
              <option value="">— No prefix —</option>
              {allPrefixes.map(pf => (
                <option key={pf.id} value={pf.id}>{pf.prefix}</option>
              ))}
            </select>
          </div>
          <Field
            label="Core Benefit(s)"
            value={p.proposedBenefits.length > 0 ? p.proposedBenefits.map((b) => `${b.title} (${b.score.toFixed(2)})`).join(', ') : '—'}
          />
          {selectedId && (
            <Link
              href={`/research/pcs/canonical-claims/${selectedId}`}
              className="text-[11px] text-pacific-600 hover:underline"
              target="_blank"
            >
              Preview selected canonical →
            </Link>
          )}
        </div>
      </div>

      {/* Action row */}
      <div className="flex items-center gap-3 mt-3 pt-3 border-t border-gray-100">
        {isApplied ? (
          <span className="text-xs px-2 py-1 rounded bg-green-50 text-green-800">
            ✓ Applied (current canonical: {p.currentCanonicalId.slice(0, 8)}…)
          </span>
        ) : (
          <>
            <button
              type="button"
              disabled={!canEdit || busy || !selectedId}
              onClick={() => onApprove(p, { canonicalId: selectedId || null, prefixId: selectedPrefixId || null })}
              className={`px-3 py-1 rounded text-xs font-medium border transition-colors ${
                canEdit && selectedId
                  ? isOverridden
                    ? 'bg-amber-600 text-white border-amber-600 hover:bg-amber-700 disabled:opacity-50'
                    : 'bg-pacific-600 text-white border-pacific-600 hover:bg-pacific-700 disabled:opacity-50'
                  : 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed'
              }`}
            >
              {busy ? 'Approving…' : isOverridden ? '✓ Approve with override' : '✓ Approve as proposed'}
            </button>
            {!selectedId && (
              <span className="text-xs text-gray-400 italic">Select a canonical to enable approval</span>
            )}
          </>
        )}
        {feedback ? (
          <span className={`ml-auto text-xs ${feedback.ok ? 'text-green-700' : 'text-red-700'}`}>
            {feedback.ok ? `✓ ${feedback.variantsCreated || 0} variant(s) created` : `✗ ${feedback.message}`}
          </span>
        ) : null}
      </div>
    </div>
  );
}

function Field({ label, value }) {
  return (
    <div className="text-xs text-gray-700">
      <span className="text-[10px] uppercase tracking-wide text-gray-500">{label}: </span>
      <span>{value}</span>
    </div>
  );
}
