/** plain-english glossary for JargonTip tooltips — keyed by lowercase term */
export const GLOSSARY: Record<string, string> = {
  // ── mathematics ────────────────────────────────────────────────
  "topology": "the study of shapes that stay the same when you stretch or bend them",
  "symmetry": "when something looks the same after you flip, rotate, or mirror it",
  "axiom": "a starting rule everyone agrees is true without needing proof",
  "proof": "a chain of logical steps that shows something must be true",
  "proof by contradiction": "assuming the opposite of what you want to prove, then showing it breaks",
  "theorem": "a math statement that has been proven true from axioms",
  "conjecture": "a math statement that seems true but nobody has proven yet",
  "irrational number": "a number that can never be written as a simple fraction",
  "countable infinity": "an infinity you can list one by one, like 1, 2, 3, 4...",
  "uncountable infinity": "an infinity too big to list, no matter how clever you are",
  "cardinality": "the size of a set — how many things are in it",
  "set": "a collection of things grouped together",
  "fibonacci sequence": "a sequence where each number is the sum of the two before it",
  "quadratic": "an expression where the highest power of the variable is 2",
  "polynomial": "a math expression with variables raised to whole-number powers",
  "exponential": "growth that doubles or triples — gets huge very fast",
  "logarithmic": "the opposite of exponential — growth that slows down over time",
  "variable": "a letter that stands in for a number you don't know yet",
  "coefficient": "the number multiplied by a variable, like the 3 in 3x",
  "composition": "feeding the output of one function into another function",
  "recursive": "defined by referring back to itself, like a mirror facing a mirror",
  "closed formula": "a shortcut that gives you any term without computing all the earlier ones",
  "oblong number": "a number that equals n times n+1, like 2, 6, 12, 20",
  "prime number": "a number only divisible by 1 and itself",
  "diagonal argument": "cantor's trick proving some infinities are bigger than others",

  // ── computer science ───────────────────────────────────────────
  "race condition": "when two things try to change the same data at the same time and collide",
  "deadlock": "when two processes each wait for the other, and neither can continue",
  "thread": "a single path of instructions running inside a program",
  "concurrency": "multiple things happening at the same time in a system",
  "mutex": "a lock that only one thread can hold, keeping others out",
  "mutual exclusion": "the rule that only one process can use a resource at a time",
  "preemption": "forcibly taking a resource away from whoever is using it",
  "non-deterministic": "the outcome can change each time you run it, even with the same inputs",
  "type system": "rules that check if you're using the right kind of data in the right place",
  "type coercion": "when a language secretly converts one data type into another",
  "state machine": "a system that can only be in one state at a time, changing via triggers",
  "transition": "the event or action that moves a state machine from one state to another",
  "boolean": "a value that is either true or false, nothing else",
  "logic gate": "a tiny circuit that takes inputs and gives one output based on a rule",
  "and gate": "outputs true only when all inputs are true",
  "or gate": "outputs true when at least one input is true",
  "xor gate": "outputs true only when the inputs disagree",
  "nand gate": "the opposite of AND — false only when all inputs are true",
  "algorithm": "a step-by-step recipe for solving a problem",
  "bubble sort": "a simple sorting method that swaps neighbors until everything is in order",
  "turing complete": "powerful enough to compute anything a real computer can",
  "compare-and-swap": "a lock-free trick: check a value and update it in one atomic step",
  "edge case": "a weird or extreme input that might break your code",

  // ── physics ────────────────────────────────────────────────────
  "reference frame": "the viewpoint from which you observe and measure motion",
  "relativity": "the idea that measurements depend on where the observer is standing",
  "inertial frame": "a viewpoint that isn't accelerating — moving at a constant speed",
  "velocity": "how fast something moves and in which direction",
  "invariant": "a quantity that stays the same no matter who measures it",
  "entropy": "when things naturally get more messy and spread out over time",
  "thermodynamics": "the science of heat, energy, and why things run down",
  "second law": "entropy in a closed system always increases — disorder always grows",
  "closed system": "a system that doesn't exchange energy or matter with its surroundings",
  "electric field": "the invisible force zone around any charged particle",
  "magnetic field": "the invisible force zone around magnets and moving charges",
  "electromagnetic wave": "light, radio, and x-rays — coupled electric and magnetic ripples",
  "dipole": "a pair of opposite charges or poles separated by a small distance",
  "field lines": "imaginary lines showing the direction a force would push a particle",
  "orbit": "the curved path an object follows around a larger body due to gravity",
  "orbital period": "the time it takes to complete one full loop around something",
  "geostationary orbit": "an orbit where a satellite stays above the same spot on earth",
  "wave-particle duality": "the strange fact that light and electrons act as both waves and particles",
  "interference pattern": "the striped pattern formed when waves overlap and reinforce or cancel",
  "uncertainty principle": "you cannot know both position and speed perfectly at the same time",
  "superposition": "being in multiple states at once until something measures you",
  "copenhagen interpretation": "the idea that a particle has no definite state until observed",
  "quantum": "the smallest possible chunk of energy or matter",
  "double-slit experiment": "firing particles through two gaps to reveal their wave nature",
  "activation energy": "the minimum energy needed to start a reaction",

  // ── biology ────────────────────────────────────────────────────
  "natural selection": "organisms with helpful traits survive more and pass those traits on",
  "selection pressure": "an environmental force that favors some traits over others",
  "fitness": "how well an organism survives and reproduces in its environment",
  "phenotype": "the visible traits of an organism — what it looks and acts like",
  "genotype": "the actual genetic code an organism carries in its DNA",
  "allele": "one version of a gene — like blue vs. brown for eye color",
  "recessive": "a gene variant that only shows up when you have two copies",
  "mutation": "a random change in DNA that may help, hurt, or do nothing",
  "genetic drift": "random changes in a population's genes, not caused by selection",
  "gene expression": "the process of turning a gene on so it makes a protein",
  "transcription": "copying a gene from DNA into a messenger RNA molecule",
  "translation": "reading messenger RNA to build a chain of amino acids",
  "promoter": "the DNA region that signals where a gene starts being read",
  "transcription factor": "a protein that attaches to DNA and switches a gene on or off",
  "mrna": "the messenger molecule that carries gene instructions to the protein factory",
  "ribosome": "the tiny machine inside cells that reads mRNA and builds proteins",
  "methylation": "adding chemical tags to DNA that silence a gene",
  "acetylation": "loosening DNA packaging so genes become accessible",
  "chromatin": "the material DNA wraps around — how tightly it's packed controls gene access",
  "trophic cascade": "a chain reaction through a food web when one species is added or removed",
  "keystone species": "a species whose removal causes the whole ecosystem to collapse",
  "food web": "the network of who-eats-whom in an ecosystem",
  "symbiosis": "two species living closely together, often helping each other",
  "emergence": "complex behavior arising from simple rules with no central controller",
  "cellular automaton": "a grid of cells that follow simple rules and produce complex patterns",
  "edge of chaos": "the sweet spot between total order and total randomness where complexity lives",

  // ── chemistry ──────────────────────────────────────────────────
  "covalent bond": "atoms sharing electrons to hold themselves together",
  "ionic bond": "atoms transferring electrons, creating charged partners that attract",
  "metallic bond": "metal atoms sharing a sea of free-roaming electrons",
  "hydrogen bond": "a weak attraction between a hydrogen and a nearby oxygen or nitrogen",
  "electronegativity": "how strongly an atom pulls electrons toward itself",
  "valence electron": "an electron in the outermost shell that participates in bonding",
  "octet": "the goal of having eight electrons in the outer shell — a stable arrangement",
  "equilibrium": "when forward and reverse processes happen at equal rates",
  "le chatelier's principle": "if you stress a system at equilibrium, it shifts to undo the stress",
  "exothermic": "a reaction that releases heat — it warms its surroundings",
  "endothermic": "a reaction that absorbs heat — it cools its surroundings",
  "catalyst": "a substance that speeds up a reaction without being used up",
  "enzyme": "a biological catalyst — a protein that speeds up one specific reaction",
  "reaction rate": "how fast reactants turn into products",
  "transition state": "the highest-energy, most unstable moment during a reaction",
  "nucleophile": "a molecule that donates electrons to attack another molecule",
  "leaving group": "the atom or group that departs during a chemical reaction",
  "stereochemistry": "the 3D arrangement of atoms in a molecule and why it matters",
  "concentration": "how much of a substance is dissolved in a given volume",

  // ── economics ──────────────────────────────────────────────────
  "margin call": "a demand to add money to your account when investments lose value",
  "short selling": "betting that a stock will go down by selling borrowed shares",
  "yield curve": "a graph showing interest rates for different loan lengths",
  "leading indicator": "a signal that changes before the economy shifts direction",
  "lagging indicator": "a signal that changes after the economy has already shifted",
  "comparative advantage": "being relatively better at producing one thing than another",
  "opportunity cost": "what you give up when you choose one option over another",
  "supply and demand": "the balance between what sellers offer and what buyers want",
  "elasticity": "how much buyers change their behavior when prices change",
  "equilibrium price": "the price where the amount supplied equals the amount demanded",
  "externality": "a cost or benefit that affects someone not involved in the transaction",
  "tragedy of the commons": "when everyone takes from a shared resource until it collapses",
  "free rider": "someone who benefits from a shared resource without contributing",
  "paradox of thrift": "when everyone saves more, total spending drops and the economy shrinks",
  "fiscal policy": "government decisions about spending and taxes to steer the economy",
  "monetary policy": "central bank decisions about interest rates and money supply",
  "quantitative easing": "a central bank buying bonds to inject money into the economy",
  "microeconomics": "the study of individual buyers, sellers, and markets",
  "macroeconomics": "the study of the whole economy — GDP, inflation, unemployment",
  "gdp": "the total value of everything a country produces in a year",
  "inflation": "when prices rise over time and money buys less",
  "deflation": "when prices fall over time — sounds good but can be devastating",
  "efficient market hypothesis": "the theory that prices already reflect all available information",
  "loss aversion": "feeling losses about twice as painfully as you enjoy equal gains",
  "endowment effect": "valuing something more just because you own it",
  "sunk cost fallacy": "continuing something because of what you already spent, not future value",
  "anchoring": "relying too heavily on the first number you see when making estimates",
  "herding": "following what everyone else does instead of thinking independently",
  "monopoly": "when one company controls an entire market with no competition",

  // ── psychology ──────────────────────────────────────────────────
  "cognitive bias": "a predictable error in thinking that everyone makes",
  "inattentional blindness": "failing to see something obvious because your focus is elsewhere",
  "confirmation bias": "only noticing evidence that supports what you already believe",
  "availability heuristic": "judging how likely something is by how easily you recall examples",
  "representativeness": "judging probability based on how well something matches a stereotype",
  "dunning-kruger effect": "beginners overestimate their skill; experts underestimate theirs",
  "halo effect": "one good quality makes you assume everything about someone is good",
  "horn effect": "one bad quality makes you assume everything about someone is bad",
  "framing effect": "how a choice is worded changes which option people pick",
  "fundamental attribution error": "blaming others' character for failures but blaming your own on luck",
  "implicit bias": "automatic associations you hold without knowing it",
  "narrative identity": "the life story you tell yourself to make sense of who you are",
  "redemption sequence": "a story pattern where bad events lead to good outcomes",
  "contamination sequence": "a story pattern where good things are spoiled by what follows",
  "theory of mind": "the ability to understand that other people have different thoughts than yours",
  "empathy": "feeling what another person feels by imagining their experience",
  "projection": "seeing your own feelings or motives in someone else",
  "schema": "a mental template you use to quickly make sense of new situations",
  "metacognition": "thinking about your own thinking",
  "looking-glass self": "we become what we think others think we are",
  "status quo bias": "preferring things to stay the way they are, even when change helps",
  "backfire effect": "when correcting a false belief actually makes people believe it more",
  "naive realism": "believing you see reality objectively while everyone else is biased",
  "system justification": "defending unfair systems even when they hurt you",

  // ── philosophy ─────────────────────────────────────────────────
  "utilitarianism": "the right action is whatever creates the most good for the most people",
  "deontology": "some actions are right or wrong regardless of their consequences",
  "categorical imperative": "act only by rules you could make universal laws for everyone",
  "virtue ethics": "focus on becoming a good person rather than following rules",
  "care ethics": "moral decisions should center who is vulnerable and who can help",
  "moral pluralism": "no single moral framework is enough — you need several",
  "hermeneutic circle": "you need the parts to understand the whole, and the whole to get the parts",
  "phenomenology": "studying experience itself — what it's like from the inside",
  "existentialism": "you define yourself through choices, not through some preset nature",
  "deconstruction": "pulling a text apart to find contradictions and hidden assumptions",
  "pragmatism": "truth is whatever works — judge ideas by their practical consequences",
  "empiricism": "all knowledge comes from observation and sensory experience",
  "rationalism": "reason and logic are the primary sources of knowledge",
  "epistemology": "the study of what knowledge is and how we get it",
  "ontology": "the study of what exists and what it means to be real",
  "sapir-whorf hypothesis": "the language you speak shapes how you think and what you can perceive",
  "liminal": "the in-between state — no longer what you were, not yet what you'll become",
  "threshold": "the point of no return where understanding permanently shifts",
  "dialectic": "reaching truth through back-and-forth argument between opposing views",
  "bad faith": "pretending you had no choice when you actually did",
  "is-ought gap": "you cannot get a moral rule from a factual statement alone",

  // ── music ──────────────────────────────────────────────────────
  "consonance": "notes that sound stable and pleasant together",
  "dissonance": "notes that clash and create tension, wanting to resolve",
  "interval": "the distance between two musical notes",
  "octave": "the same note at double the frequency — sounds like a higher twin",
  "tritone": "the interval splitting the octave exactly in half — the devil's interval",
  "harmony": "multiple notes sounding together in a pleasing or intentional way",
  "timbre": "the unique color or texture of a sound — why a flute and trumpet sound different",
  "polyrhythm": "two different rhythmic patterns played at the same time",
  "syncopation": "accenting beats where you don't expect them — the source of groove",
  "tempo": "how fast or slow the music goes, measured in beats per minute",
  "drone": "a single sustained note that everything else is built on top of",
  "clave": "a rhythmic pattern that organizes all the other parts in afro-cuban music",
  "resolution": "when tension in music relaxes into a stable, restful sound",
  "chromesthesia": "involuntarily seeing colors when hearing sounds",
  "overtone": "the higher, quieter frequencies that give each instrument its unique color",
  "counterpoint": "two or more independent melodies woven together at the same time",

  // ── visual arts ────────────────────────────────────────────────
  "negative space": "the empty area around and between the subjects in a composition",
  "visual composition": "how elements are arranged within a frame or canvas",
  "rule of thirds": "placing key elements at the intersections of a 3x3 grid",
  "golden ratio": "a mathematical proportion (~1.618) found in nature and pleasing designs",
  "leading lines": "visual paths that pull your eye through an image",
  "juxtaposition": "placing two contrasting things side by side to create meaning",
  "hierarchy": "signaling what to look at first, second, and third in a design",
  "contrast": "making differences obvious — light vs dark, big vs small",
  "hue": "the pure name of a color — red, blue, green, yellow",
  "saturation": "how vivid or muted a color is — neon versus pastel",
  "complementary colors": "colors opposite each other on the color wheel that create tension",
  "analogous colors": "colors next to each other on the color wheel that feel harmonious",
  "monochrome": "using only one color in different shades and tones",
  "gestalt": "the brain's tendency to see whole patterns rather than individual parts",
  "figure-ground": "your brain deciding what's the subject and what's the background",

  // ── writing ────────────────────────────────────────────────────
  "rhetoric": "the art of persuading people through language",
  "ethos": "persuading by showing you're credible and trustworthy",
  "pathos": "persuading by appealing to emotions",
  "logos": "persuading through logic and evidence",
  "thesis": "the central claim an argument is built around",
  "genre": "a category of writing with its own rules and reader expectations",
  "voice": "the personality and style that comes through in someone's writing",
  "revision": "rethinking and restructuring writing — not just fixing typos",
  "counterargument": "presenting the opposing view before showing why yours is stronger",
  "inverted pyramid": "putting the most important information first, details later",
  "unreliable narrator": "a storyteller you can't fully trust — they hide or distort facts",
  "subtext": "the hidden meaning beneath what's actually said or written",
  "implied reader": "the imagined audience a writer has in mind while writing",
  "narrative arc": "the shape of a story — setup, rising tension, climax, resolution",
  "refrain": "a repeated phrase or line that builds rhythm and emphasis",

  // ── cross-cutting concepts ─────────────────────────────────────
  "agency": "the power to make choices and take action on your own",
  "feedback loop": "when the output of a system circles back to influence the input",
  "abstraction": "hiding complex details behind a simpler idea or interface",
  "model": "a simplified version of something real, built to help you understand it",
  "spectrum": "a range between two extremes, with everything in between",
  "heuristic": "a mental shortcut that's usually right but sometimes wrong",
  "fallacy of composition": "assuming what's true for one part is true for the whole",
  "calibration": "how well your confidence matches your actual accuracy",
  "parsimony": "the simplest explanation that accounts for all the facts",
  "isomorphism": "when two different things share the same underlying structure",
  "phase transition": "a sudden shift from one state to another, like water freezing to ice",
  "signal-to-noise ratio": "how much useful information versus random junk is in a message",
  "degrees of freedom": "the number of independent choices you can make in a system",
  "constraint": "a limitation that actually helps by narrowing the possible solutions",
  "iteration": "repeating a process, improving a little each time",
  "bifurcation": "when a system splits into two possible paths at a critical point",
};
