/**
 * Ancestry Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection, and wires
 * the two Vercel cron jobs as CF Workers scheduled() triggers.
 *
 * Why this file exists:
 *   1. OpenNext on CF Workers does NOT honour next.config.ts headers().
 *      We wrap the fetch handler with wrapWithSecurityHeaders.
 *   2. Vercel crons (vercel.json) don't exist on CF Workers — the two
 *      crons are registered in wrangler.jsonc as cron_triggers and
 *      dispatched here via the WORKER_SELF_REFERENCE service binding.
 *   3. OpenNext emits Durable Object classes that must be re-exported or
 *      wrangler drops them at deploy time.
 *
 * Cron schedule (mirrors vercel.json):
 *   "* /5 * * * *"  → /api/cron/notifications   (every 5 minutes)
 *   "0 8 * * 1"     → /api/cron/weekly-digest   (Mondays 08:00 UTC)
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`; absent on fresh clone.
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  HARBOUR_DEFAULT_CSP,
} from "@windedvertigo/security";

// Re-export Durable Object classes so wrangler keeps them in the deployed
// worker. Without these, OpenNext's queue / tag-cache DOs fail at runtime.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

// ─── Env type ───────────────────────────────────────────────────────────────

interface AncestryWorkerEnv {
  /** Service binding — routes cron requests directly to this worker */
  WORKER_SELF_REFERENCE: { fetch: (req: Request) => Promise<Response> };
  CRON_SECRET?: string;
  CF_WORKERS_ENV?: string;
}

// ─── Scheduled (cron) handler ────────────────────────────────────────────────

const CRON_ROUTES: Record<string, string> = {
  "*/5 * * * *": "/api/cron/notifications",
  "0 8 * * 1":   "/api/cron/weekly-digest",
};

async function scheduled(
  controller: { cron: string },
  env: AncestryWorkerEnv,
  ctx: { waitUntil: (p: Promise<unknown>) => void },
): Promise<void> {
  const path = CRON_ROUTES[controller.cron];
  if (!path) {
    console.warn(`[ancestry:scheduled] unknown cron: ${controller.cron}`);
    return;
  }

  const headers: HeadersInit = {};
  if (env.CRON_SECRET) {
    headers["Authorization"] = `Bearer ${env.CRON_SECRET}`;
  }

  // Use WORKER_SELF_REFERENCE (service binding) to route the request directly
  // to this worker's fetch handler without hitting the public internet.
  ctx.waitUntil(
    env.WORKER_SELF_REFERENCE.fetch(
      new Request(`https://ancestry-self${path}`, { method: "GET", headers }),
    ).then((r) => {
      if (!r.ok) {
        console.error(
          `[ancestry:scheduled] cron ${controller.cron} (${path}) → ${r.status}`,
        );
      } else {
        console.log(
          `[ancestry:scheduled] cron ${controller.cron} (${path}) → ${r.status}`,
        );
      }
    }),
  );
}

// ─── Default export ──────────────────────────────────────────────────────────

export default {
  // Wrap fetch with security headers (CSP, HSTS, etc.)
  // OpenNext's next.config.ts headers() are ignored on CF Workers.
  fetch: wrapWithSecurityHeaders(openNextHandler, {
    csp: HARBOUR_DEFAULT_CSP,
    skipPaths: [/^\/cdn-cgi\//],
  }).fetch,

  scheduled,
};
