/**
 * Vault Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection, and wires the
 * daily Notion sync as a CF Workers scheduled() trigger.
 *
 * Why this file exists:
 *   1. OpenNext on CF Workers does NOT honour next.config.ts headers().
 *      We wrap the fetch handler with wrapWithSecurityHeaders.
 *   2. Vercel crons (vercel.json) don't exist on CF Workers — the daily
 *      sync cron is registered in wrangler.jsonc and dispatched here.
 *   3. OpenNext emits Durable Object classes that must be re-exported or
 *      wrangler drops them at deploy time.
 *
 * Cron schedule (mirrors vercel.json):
 *   "0 6 * * *"  → /harbour/vertigo-vault/api/cron/sync  (daily 06:00 UTC)
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`; absent on fresh clone.
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  HARBOUR_DEFAULT_CSP,
} from "@windedvertigo/security";

import { scheduled as vaultScheduled } from "./lib/scheduled";

// Re-export Durable Object classes so wrangler keeps them in the deployed
// worker. Without these, OpenNext's queue / tag-cache DOs fail at runtime.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

// ─── Env type ───────────────────────────────────────────────────────────────

interface VaultWorkerEnv {
  /** Service binding — routes cron requests directly to this worker */
  WORKER_SELF_REFERENCE: { fetch: (req: Request) => Promise<Response> };
  CRON_SECRET?: string;
  CF_WORKERS_ENV?: string;
  NEXT_PUBLIC_APP_URL?: string;
  [key: string]: unknown;
}

// ─── Main export ─────────────────────────────────────────────────────────────

export default {
  fetch: wrapWithSecurityHeaders(openNextHandler.fetch, {
    csp: HARBOUR_DEFAULT_CSP,
  }),

  async scheduled(
    controller: ScheduledController,
    env: VaultWorkerEnv,
    ctx: ExecutionContext,
  ) {
    await vaultScheduled(controller, env as Record<string, string>, ctx);
  },
};
