"use client";

/**
 * InvoicePreview — renders a branded invoice as printable HTML.
 *
 * Dual-purpose: on-screen preview + print-to-PDF via window.print().
 * The HTML is generated server-side by buildInvoiceHtml() from trusted
 * invoice data — it does NOT contain user-generated content that could
 * be an XSS vector. The same HTML is sent via Resend for email delivery.
 */

interface InvoicePreviewProps {
  /** Trusted HTML generated by buildInvoiceHtml() — not user input */
  html: string;
}

export function InvoicePreview({ html }: InvoicePreviewProps) {
  // SAFETY: html is generated by buildInvoiceHtml() from Notion database
  // fields (project names, member names, hours, rates). These are trusted
  // internal data, not arbitrary user HTML input.
  return (
    <div
      className="invoice-preview"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
