/**
 * POST /api/strategy/create-campaign
 *
 * Convert a strategic campaign brief (from /strategy page) into a concrete
 * draft CRM campaign using Claude Sonnet. Drafts the name, type, audience
 * filter, and email body; then writes a single row to Supabase via the
 * existing campaigns write path.
 *
 * Auth is enforced upstream by middleware.ts.
 */

import { NextRequest } from "next/server";
import { callClaude, parseJsonResponse } from "@/lib/ai/client";
import { upsertCampaignToSupabase } from "@/lib/supabase/campaigns";
import { json, error } from "@/lib/api-helpers";
import type { CampaignType, AudienceFilter } from "@/lib/notion/types";

export const maxDuration = 60;

const VALID_CAMPAIGN_TYPES: CampaignType[] = [
  "event-based",
  "recurring cadence",
  "one-off blast",
];

interface CreateCampaignFromStrategyBody {
  strategicName: string;
  objective: string;
  keyMetrics: string[];
  owner: string;
  matchKeywords: string[];
}

interface ClaudeOutput {
  campaignName: string;
  campaignType: string;
  campaignStatus: string;
  audienceDescription: string;
  audienceFilters: AudienceFilter;
  draftSubject: string;
  draftBody: string;
  notes: string;
}

const SYSTEM_PROMPT = `You are a marketing strategist for winded.vertigo, a learning-design collective. Write in lowercase, british spelling, playful, human, dynamic, no exclamation marks. Convert a strategic campaign brief into a concrete CRM campaign plan with a draft outreach email.
Return ONLY valid JSON matching this exact schema (no extra fields, no markdown): { "campaignName": string (≤80 chars, lowercase, evocative), "campaignType": one of ["event-based","recurring cadence","one-off blast"], "campaignStatus": "draft", "audienceDescription": string (1 sentence describing who this targets), "audienceFilters": { "fitRating"?: string[], "relationship"?: string[], "regions"?: string[] } (use null/missing for unset), "draftSubject": string (email subject line, ≤60 chars), "draftBody": string (email body, 150-250 words, no greeting placeholder, ready to personalize), "notes": string (internal notes for payton — what's strategic about this, why these audience filters, anything claude is uncertain about). }`;

function buildUserPrompt(body: CreateCampaignFromStrategyBody): string {
  return [
    `Strategic campaign: ${body.strategicName}`,
    `Objective: ${body.objective}`,
    `Owner: ${body.owner}`,
    "Key success metrics:",
    ...body.keyMetrics.map((m) => `- ${m}`),
    `Keywords: ${body.matchKeywords.join(", ")}`,
    "",
    "Draft a CRM campaign + first-draft email body.",
  ].join("\n");
}

export async function POST(req: NextRequest) {
  const body = (await req.json().catch(() => null)) as
    | CreateCampaignFromStrategyBody
    | null;

  if (!body || !body.strategicName || !body.objective) {
    return error("strategicName and objective are required");
  }

  let draft: ClaudeOutput;
  let costUsd = 0;
  try {
    const result = await callClaude({
      feature: "email-draft",
      system: SYSTEM_PROMPT,
      userMessage: buildUserPrompt(body),
      userId: "strategy-page",
      maxTokens: 2048,
      temperature: 0.5,
      timeoutMs: 60_000,
    });
    costUsd = result.costUsd;
    draft = parseJsonResponse<ClaudeOutput>(result.text);
  } catch (err) {
    console.error("[api/strategy/create-campaign] claude call failed:", err);
    const message = err instanceof Error ? err.message : "ai call failed";
    return error(`failed to draft campaign: ${message}`, 500);
  }

  // ── validate type, fall back to recurring cadence with warning ──
  let typeWarning = "";
  let campaignType: CampaignType;
  if (VALID_CAMPAIGN_TYPES.includes(draft.campaignType as CampaignType)) {
    campaignType = draft.campaignType as CampaignType;
  } else {
    typeWarning = `\n\n[note: claude suggested type "${draft.campaignType}" which isn't a valid CampaignType — fell back to "recurring cadence"]`;
    campaignType = "recurring cadence";
  }

  const campaignId = crypto.randomUUID();
  const name = (draft.campaignName ?? body.strategicName).slice(0, 200);

  const notes = [
    "## strategic intent",
    draft.notes ?? "",
    "",
    "## audience reasoning",
    draft.audienceDescription ?? "",
    "",
    "## draft email subject",
    draft.draftSubject ?? "",
    "",
    "## draft email body",
    draft.draftBody ?? "",
    typeWarning,
    "",
    `[generated by claude on ${new Date().toISOString().slice(0, 10)} from strategy page · cost ~$${costUsd.toFixed(4)}]`,
  ].join("\n");

  try {
    await upsertCampaignToSupabase(campaignId, {
      name,
      type: campaignType,
      status: "draft",
      event_ids: [],
      audience_filters: (draft.audienceFilters ?? {}) as Record<string, unknown>,
      owner: body.owner ?? null,
      start_date: null,
      end_date: null,
      notes,
    });
  } catch (err) {
    console.error("[api/strategy/create-campaign] supabase upsert failed:", err);
    return error("failed to create campaign", 500);
  }

  return json(
    {
      campaignId,
      redirectUrl: `/campaigns/${campaignId}`,
      model: "claude-sonnet-4-6",
      costUsd,
    },
    201,
  );
}
