#!/usr/bin/env bash
# pocket-prompts-migrate.sh
#
# Turnkey migration of the ghandoff/pocket-prompts repo from Vercel to a
# Cloudflare Worker (wv-pocket-prompts). Run from the root of the
# pocket-prompts repo on your laptop, NOT from windedvertigo.
#
# Usage:
#   ./pocket-prompts-migrate.sh --dry-run    # preview every change
#   ./pocket-prompts-migrate.sh              # apply changes + commit
#
# Reads from the current dir, writes wrangler.jsonc / open-next.config.ts /
# worker.ts, edits package.json + .gitignore, scrubs @vercel/* and VERCEL_URL
# refs, and commits the result on branch claude/migrate-to-cloudflare-workers.
#
# Does NOT push. Does NOT deploy. Does NOT touch secrets. After running,
# follow docs/pocket-prompts-cf-migration.md in the windedvertigo repo.

set -euo pipefail

DRY_RUN=false
for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
  esac
done

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[err]\033[0m %s\n' "$*" >&2; exit 1; }

write_or_preview() {
  local path="$1" content="$2"
  if $DRY_RUN; then
    echo "--- would write $path ---"
    printf '%s\n' "$content"
    echo "--- end $path ---"
  else
    printf '%s\n' "$content" > "$path"
    echo "  wrote $path"
  fi
}

[[ -f package.json ]] || die "package.json not found — run this from the pocket-prompts repo root"

say "Detecting framework..."
if grep -q '"next"' package.json; then
  FRAMEWORK="next"
elif grep -qE '"(nuxt|astro|remix)"' package.json; then
  die "Detected non-Next.js framework. This script only handles Next.js. Migrate manually."
else
  die "No supported framework detected in package.json (need: next)."
fi
echo "  framework: $FRAMEWORK"

say "Step 1/6: Checking for @vercel/* deps and VERCEL_URL fallbacks..."
VERCEL_DEPS=$(grep -oE '"@vercel/[a-z-]+"' package.json | sort -u || true)
if [[ -n "$VERCEL_DEPS" ]]; then
  echo "  found Vercel deps:"
  echo "$VERCEL_DEPS" | sed 's/^/    /'
fi
VERCEL_URL_FILES=$(grep -rl "process\.env\.VERCEL_URL" --include='*.ts' --include='*.tsx' --include='*.js' --include='*.mjs' . 2>/dev/null | grep -v node_modules || true)
if [[ -n "$VERCEL_URL_FILES" ]]; then
  echo "  files referencing VERCEL_URL:"
  echo "$VERCEL_URL_FILES" | sed 's/^/    /'
fi

say "Step 2/6: Writing wrangler.jsonc..."
WRANGLER_CONTENT='{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "wv-pocket-prompts",
  "main": "worker.ts",
  "account_id": "097c92553b268f8360b74f625f6d980a",
  "compatibility_date": "2025-04-01",
  "compatibility_flags": ["nodejs_compat"],
  "workers_dev": true,

  "assets": {
    "directory": ".open-next/assets",
    "binding": "ASSETS"
  },

  "services": [
    { "binding": "WORKER_SELF_REFERENCE", "service": "wv-pocket-prompts" }
  ],

  "vars": {
    "CF_WORKERS_ENV": "1"
  }

  // Secrets — set via: wrangler secret put <NAME> --name wv-pocket-prompts
  // Add routes block here if you want a custom domain.
}'
write_or_preview "wrangler.jsonc" "$WRANGLER_CONTENT"

say "Step 3/6: Writing open-next.config.ts..."
OPEN_NEXT='import { defineCloudflareConfig } from "@opennextjs/cloudflare";
export default defineCloudflareConfig({});'
write_or_preview "open-next.config.ts" "$OPEN_NEXT"

say "Step 4/6: Writing worker.ts..."
WORKER='// @ts-ignore — generated by `npx opennextjs-cloudflare build`; absent on fresh clone.
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

export default {
  fetch: openNextHandler.fetch,
};'
write_or_preview "worker.ts" "$WORKER"

say "Step 5/6: Editing package.json..."
if $DRY_RUN; then
  echo "  would add deps: @opennextjs/cloudflare, @cloudflare/workers-types, wrangler"
  echo "  would add scripts: build:cf, preview:cf, deploy:cf"
  echo "  would remove deps: $VERCEL_DEPS"
else
  node - <<'NODE_EOF'
const fs = require("fs");
const p = JSON.parse(fs.readFileSync("package.json", "utf8"));
p.scripts = p.scripts || {};
p.scripts["build:cf"] = "next build && opennextjs-cloudflare build --skipNextBuild";
p.scripts["preview:cf"] = "wrangler dev";
p.scripts["deploy:cf"] = "npm run build:cf && wrangler deploy";
p.dependencies = p.dependencies || {};
p.dependencies["@opennextjs/cloudflare"] = "^1.19.4";
p.devDependencies = p.devDependencies || {};
p.devDependencies["@cloudflare/workers-types"] = "^4.20260426.1";
p.devDependencies["wrangler"] = "^3.114.0";
// Strip @vercel/* runtime deps (build/CLI like @vercel/next stay if present, but
// shouldn't be in dependencies normally).
for (const section of ["dependencies", "devDependencies"]) {
  for (const k of Object.keys(p[section] || {})) {
    if (k.startsWith("@vercel/")) {
      console.log(`  removing ${section}.${k}`);
      delete p[section][k];
    }
  }
}
fs.writeFileSync("package.json", JSON.stringify(p, null, 2) + "\n");
console.log("  package.json updated");
NODE_EOF
fi

say "Step 6/6: Updating .gitignore..."
if $DRY_RUN; then
  echo "  would add .open-next/ to .gitignore"
else
  touch .gitignore
  if ! grep -qE '^\.open-next/?$' .gitignore; then
    printf '\n.open-next/\n' >> .gitignore
    echo "  added .open-next/ to .gitignore"
  fi
fi

if [[ -n "$VERCEL_URL_FILES" ]] && ! $DRY_RUN; then
  say "Rewriting VERCEL_URL fallbacks..."
  while IFS= read -r file; do
    # Replace `process.env.VERCEL_URL ? \`https://\${process.env.VERCEL_URL}\` : ...`
    # with process.env.WORKER_URL ?? (the original fallback).
    # Conservative: only echoes which files need manual review. Awk regex on
    # arbitrary code is risky.
    echo "  REVIEW: $file"
  done <<< "$VERCEL_URL_FILES"
  warn "VERCEL_URL refs above need manual edit. Recommended: introduce WORKER_URL env var and replace fallbacks with: process.env.WORKER_URL ?? 'http://localhost:3000'"
fi

if ! $DRY_RUN; then
  say "Committing..."
  git checkout -B claude/migrate-to-cloudflare-workers
  git add -A
  if git diff --cached --quiet; then
    warn "Nothing to commit (working tree clean after edits)."
  else
    git commit -m "chore: migrate to Cloudflare Workers via OpenNext

- Add wrangler.jsonc targeting wv-pocket-prompts worker
- Add open-next.config.ts + worker.ts
- Add @opennextjs/cloudflare + wrangler deps
- Add build:cf / preview:cf / deploy:cf scripts
- Strip @vercel/* runtime deps
- Ignore .open-next/

Manual follow-ups:
- Review VERCEL_URL fallbacks listed by the migration script
- Set secrets via wrangler secret put
- npm install && npm run deploy:cf
- Verify on wv-pocket-prompts.windedvertigo.workers.dev
- Delete Vercel project once confirmed working"
    echo ""
    say "Done. Next steps:"
    cat <<'EOT'
  1. npm install
  2. Set secrets:
       wrangler secret put SECRET_NAME --name wv-pocket-prompts
     (Repeat for each Vercel env var your app actually uses.)
  3. npm run deploy:cf
  4. curl -sI https://wv-pocket-prompts.windedvertigo.workers.dev/
  5. If it works: git push origin claude/migrate-to-cloudflare-workers, open PR.
  6. Once merged + verified in prod: delete the Vercel pocket-prompts project.

  Full playbook: docs/pocket-prompts-cf-migration.md (in windedvertigo monorepo)
EOT
  fi
else
  say "Dry run complete. Re-run without --dry-run to apply."
fi
