#!/usr/bin/env node
/**
 * sync-footer.mjs
 *
 * Single source of truth: packages/tokens/footer.html
 *
 * This script reads that file and:
 *   1. Generates packages/tokens/footer-html.ts  (so creaseworks can import it)
 *   2. Injects the HTML into every static page in apps/site/
 *
 * Run from the repo root:
 *   node scripts/sync-footer.mjs
 *   — or —
 *   npm run sync:footer
 */

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

/* ── 1. read the canonical footer ─────────────────────────────────── */
const footerPath = resolve(root, "packages/tokens/footer.html");
const canonicalFooter = readFileSync(footerPath, "utf-8").trim();
console.log("source: packages/tokens/footer.html\n");

/* ── 2. generate TypeScript wrapper ───────────────────────────────── */
const tsContent = `/**
 * AUTO-GENERATED by scripts/sync-footer.mjs — do not edit.
 * Edit packages/tokens/footer.html instead, then run: npm run sync:footer
 */
export const WV_FOOTER_HTML = ${JSON.stringify(canonicalFooter)};
`;

const tsPath = resolve(root, "packages/tokens/footer-html.ts");
writeFileSync(tsPath, tsContent, "utf-8");
console.log("  generated: packages/tokens/footer-html.ts");

/* ── 3. inject into all static HTML pages ─────────────────────────── */
function walkHtml(dir) {
  const results = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory() && entry.name !== "node_modules") {
      results.push(...walkHtml(full));
    } else if (entry.isFile() && entry.name.endsWith(".html")) {
      results.push(full);
    }
  }
  return results;
}

const siteDir = resolve(root, "apps/site");
const htmlFiles = walkHtml(siteDir);
const footerRe = /<footer class="wv-footer">[\s\S]*?<\/footer>/;

let updated = 0;
let inserted = 0;

for (const file of htmlFiles) {
  let html = readFileSync(file, "utf-8");

  if (footerRe.test(html)) {
    const newHtml = html.replace(footerRe, canonicalFooter);
    if (newHtml !== html) {
      writeFileSync(file, newHtml, "utf-8");
      updated++;
      console.log(`  updated: ${file.replace(root + "/", "")}`);
    } else {
      console.log(`  (no change): ${file.replace(root + "/", "")}`);
    }
  } else if (html.includes("</body>")) {
    const newHtml = html.replace("</body>", `\n  ${canonicalFooter}\n</body>`);
    writeFileSync(file, newHtml, "utf-8");
    inserted++;
    console.log(`  inserted: ${file.replace(root + "/", "")}`);
  } else {
    console.log(`  skipped (no </body>): ${file.replace(root + "/", "")}`);
  }
}

console.log(`\ndone. ts generated, ${updated} pages updated, ${inserted} inserted, ${htmlFiles.length} total files.`);
