'use client';

/**
 * Wave 5.6 — Reformulation suggestion modal.
 *
 * Opens from RequestDetailSideSheet when a Request is a safety-flagged
 * label-drift. Prompts RA for the flagged ingredient / dose / demographic,
 * calls POST /api/pcs/labels/[id]/suggest-reformulation, and renders the
 * suggestions as traffic-light cards.
 *
 * ADVISORY ONLY — banners make that clear. Two write actions are available,
 * both explicit: "Copy as action plan" (clipboard) and "Mark this approach
 * as accepted" (appends a note to the originating Request, does NOT resolve
 * it — RA still does the actual reformulation work).
 */

import { useEffect, useState } from 'react';

const APPROACH_LABELS = {
  'dose-reduction': 'Dose reduction',
  'form-swap': 'Form swap',
  'substitution': 'Ingredient substitution',
  'demographic-scope': 'Narrow demographic',
  'add-warning': 'Add warning label',
};

function riskTone(risk) {
  const r = Number(risk) || 0;
  if (r < 0.34) return { bg: 'bg-green-100', text: 'text-green-800', label: 'Low risk' };
  if (r < 0.67) return { bg: 'bg-amber-100', text: 'text-amber-800', label: 'Medium risk' };
  return { bg: 'bg-red-100', text: 'text-red-800', label: 'High risk' };
}

function formatSuggestionForActionPlan(s, meta) {
  const lines = [
    `Reformulation approach: ${APPROACH_LABELS[s.approach] || s.approach}`,
    meta?.flaggedIngredient ? `Flagged ingredient: ${meta.flaggedIngredient}` : null,
    s.newIngredient ? `Proposed ingredient: ${s.newIngredient}` : null,
    s.newDose != null ? `Proposed dose: ${s.newDose}${s.newDoseUnit ? ' ' + s.newDoseUnit : ''}` : null,
    s.newWarningText ? `Proposed warning: ${s.newWarningText}` : null,
    '',
    `What changes: ${s.changeSummary}`,
    `Rationale: ${s.rationale}`,
    `Regulatory risk (self-assessed): ${(Number(s.regulatoryRisk) || 0).toFixed(2)}`,
  ].filter(Boolean);
  if (s.warnings?.length) {
    lines.push('', 'Things to double-check:');
    for (const w of s.warnings) lines.push(`  - ${w}`);
  }
  lines.push('', `— AI-generated by reformulation-suggester (advisory only).`);
  return lines.join('\n');
}

export default function ReformulationSuggestionModal({
  requestId,
  labelId,
  safetyEvidenceId,
  existingNotes,
  onClose,
  onNotesAppended,
}) {
  const [flaggedIngredient, setFlaggedIngredient] = useState('');
  const [currentDose, setCurrentDose] = useState('');
  const [currentDoseUnit, setCurrentDoseUnit] = useState('mg');
  const [demographic, setDemographic] = useState('');
  const [loading, setLoading] = useState(false);
  const [costGate, setCostGate] = useState(null);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [acceptingIdx, setAcceptingIdx] = useState(null);
  const [acceptedIdx, setAcceptedIdx] = useState(new Set());

  useEffect(() => {
    function onKey(e) { if (e.key === 'Escape') onClose?.(); }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [onClose]);

  async function runSuggester(confirmCost = false) {
    if (!flaggedIngredient.trim()) {
      setError('Flagged ingredient is required.');
      return;
    }
    setLoading(true);
    setError(null);
    setCostGate(null);
    try {
      const payload = {
        flaggedIngredient: flaggedIngredient.trim(),
        currentDose: currentDose === '' ? undefined : Number(currentDose),
        currentDoseUnit: currentDoseUnit || undefined,
        demographic: demographic || undefined,
        safetyEvidenceId: safetyEvidenceId || undefined,
      };
      if (confirmCost) payload.confirmCost = true;

      const res = await fetch(`/api/pcs/labels/${labelId}/suggest-reformulation`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (res.status === 402 && data?.error === 'cost-confirm-required') {
        setCostGate(data);
        return;
      }
      if (!res.ok) {
        setError(data?.error || 'Failed to generate suggestions');
        return;
      }
      setResult(data);
    } catch (err) {
      setError(err?.message || 'Failed to generate suggestions');
    } finally {
      setLoading(false);
    }
  }

  async function copyActionPlan(suggestion) {
    try {
      const text = formatSuggestionForActionPlan(suggestion, result);
      await navigator.clipboard.writeText(text);
    } catch {
      /* clipboard failures are non-fatal — user can still read the card */
    }
  }

  async function markAccepted(suggestion, idx) {
    setAcceptingIdx(idx);
    setError(null);
    try {
      const timestamp = new Date().toISOString().slice(0, 10);
      const appendedBlock = [
        '',
        `--- Reformulation direction accepted (${timestamp}) ---`,
        formatSuggestionForActionPlan(suggestion, result),
      ].join('\n');
      const newNotes = (existingNotes || '').trimEnd() + '\n' + appendedBlock;

      const res = await fetch(`/api/pcs/requests/${requestId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ requestNotes: newNotes }),
      });
      const updated = await res.json();
      if (!res.ok) {
        setError(updated?.error || 'Failed to append note to request');
        return;
      }
      setAcceptedIdx(prev => {
        const next = new Set(prev);
        next.add(idx);
        return next;
      });
      onNotesAppended?.(updated);
    } catch (err) {
      setError(err?.message || 'Failed to append note to request');
    } finally {
      setAcceptingIdx(null);
    }
  }

  return (
    <div
      className="fixed inset-0 z-[60] flex items-center justify-center"
      role="dialog"
      aria-modal="true"
      aria-label="Suggest reformulation"
    >
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative bg-white rounded-lg shadow-2xl w-[min(720px,94vw)] max-h-[90vh] flex flex-col">
        <header className="flex items-center justify-between px-5 py-3 border-b border-gray-200">
          <h2 className="text-sm font-semibold text-gray-900">
            Suggest reformulation — AI assistant
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 text-xl leading-none"
            aria-label="Close"
          >
            ×
          </button>
        </header>

        <div className="px-5 py-4 bg-amber-50 border-b border-amber-200">
          <p className="text-xs text-amber-900">
            <span className="font-semibold">Advisory only.</span> Suggestions are AI-generated
            from the backing PCS and safety evidence. Nothing is written to the label, PCS, or
            Request. You must validate every approach with supplier, formulation, and QA
            partners before action. Disease-claim verbs are filtered; the disease-claim
            disclaimer still applies.
          </p>
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
          {!result && (
            <div className="space-y-3">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Flagged ingredient <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={flaggedIngredient}
                  onChange={e => setFlaggedIngredient(e.target.value)}
                  placeholder="e.g. magnesium oxide"
                  className="w-full text-sm border border-gray-300 rounded-md px-2 py-1 focus:ring-1 focus:ring-pacific-500 focus:border-pacific-500"
                  autoFocus
                />
              </div>
              <div className="grid grid-cols-3 gap-2">
                <div className="col-span-2">
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Current dose
                  </label>
                  <input
                    type="number"
                    value={currentDose}
                    onChange={e => setCurrentDose(e.target.value)}
                    placeholder="160"
                    className="w-full text-sm border border-gray-300 rounded-md px-2 py-1 focus:ring-1 focus:ring-pacific-500 focus:border-pacific-500"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Unit</label>
                  <select
                    value={currentDoseUnit}
                    onChange={e => setCurrentDoseUnit(e.target.value)}
                    className="w-full text-sm border border-gray-300 rounded-md px-2 py-1 focus:ring-1 focus:ring-pacific-500 focus:border-pacific-500"
                  >
                    <option value="mg">mg</option>
                    <option value="mcg">mcg</option>
                    <option value="g">g</option>
                    <option value="IU">IU</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Demographic (if the safety signal is population-specific)
                </label>
                <input
                  type="text"
                  value={demographic}
                  onChange={e => setDemographic(e.target.value)}
                  placeholder="e.g. pediatric, pregnant, ≥65"
                  className="w-full text-sm border border-gray-300 rounded-md px-2 py-1 focus:ring-1 focus:ring-pacific-500 focus:border-pacific-500"
                />
              </div>

              {costGate && (
                <div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-xs text-amber-900 space-y-2">
                  <p>
                    <span className="font-semibold">Confirm cost:</span>{' '}
                    Estimated ~${costGate.cost?.estUsd?.toFixed?.(4) ?? '0.00'} for this run
                    (prompt version <code>{costGate.promptVersion}</code>, {costGate.claimCount ?? 0} backing claims).
                  </p>
                  <button
                    onClick={() => runSuggester(true)}
                    disabled={loading}
                    className="px-3 py-1 text-xs font-medium text-white bg-amber-700 rounded hover:bg-amber-800 disabled:opacity-50"
                  >
                    {loading ? 'Generating…' : 'Confirm and generate'}
                  </button>
                </div>
              )}

              {error && <p className="text-xs text-red-600">{error}</p>}

              {!costGate && (
                <div className="flex justify-end">
                  <button
                    onClick={() => runSuggester(false)}
                    disabled={loading}
                    className="px-4 py-2 text-sm font-medium text-white bg-pacific-600 rounded-md hover:bg-pacific-700 disabled:opacity-50"
                  >
                    {loading ? 'Generating…' : 'Generate suggestions'}
                  </button>
                </div>
              )}
            </div>
          )}

          {result && (
            <div className="space-y-4">
              <div className="text-xs text-gray-500 flex items-center justify-between">
                <span>
                  Prompt <code>{result.promptVersion}</code> · model{' '}
                  <code>{result.model}</code> · est ${result.cost?.estUsd?.toFixed?.(4)}
                </span>
                <button
                  onClick={() => { setResult(null); setError(null); }}
                  className="text-pacific-600 hover:underline"
                >
                  ← Start over
                </button>
              </div>

              {result.suggestions?.length > 0 ? (
                result.suggestions.map((s, idx) => {
                  const tone = riskTone(s.regulatoryRisk);
                  const accepted = acceptedIdx.has(idx);
                  return (
                    <div key={idx} className="border border-gray-200 rounded-md p-4 space-y-3">
                      <div className="flex items-start justify-between gap-2">
                        <div>
                          <p className="text-xs uppercase text-gray-500 font-semibold">
                            {APPROACH_LABELS[s.approach] || s.approach}
                          </p>
                          <p className="text-sm text-gray-900 mt-1">{s.changeSummary}</p>
                        </div>
                        <span className={`text-[10px] uppercase font-semibold px-2 py-1 rounded-full shrink-0 ${tone.bg} ${tone.text}`}>
                          {tone.label} ({(Number(s.regulatoryRisk) || 0).toFixed(2)})
                        </span>
                      </div>

                      {(s.newIngredient || s.newDose != null || s.newWarningText) && (
                        <dl className="grid grid-cols-3 gap-x-2 gap-y-1 text-xs bg-gray-50 rounded p-2 border border-gray-200">
                          {s.newIngredient && (
                            <>
                              <dt className="text-gray-500">New ingredient</dt>
                              <dd className="col-span-2 font-mono text-gray-900">{s.newIngredient}</dd>
                            </>
                          )}
                          {s.newDose != null && (
                            <>
                              <dt className="text-gray-500">New dose</dt>
                              <dd className="col-span-2 font-mono text-gray-900">
                                {s.newDose}{s.newDoseUnit ? ' ' + s.newDoseUnit : ''}
                              </dd>
                            </>
                          )}
                          {s.newWarningText && (
                            <>
                              <dt className="text-gray-500">Warning text</dt>
                              <dd className="col-span-2 text-gray-900">{s.newWarningText}</dd>
                            </>
                          )}
                        </dl>
                      )}

                      <p className="text-xs text-gray-700">
                        <span className="font-semibold text-gray-600">Rationale: </span>
                        {s.rationale}
                      </p>

                      {s.warnings?.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {s.warnings.map((w, i) => (
                            <span
                              key={i}
                              className={`text-[11px] px-2 py-0.5 rounded-full border ${
                                typeof w === 'string' && w.startsWith('SAFETY:')
                                  ? 'bg-red-50 border-red-200 text-red-800'
                                  : 'bg-amber-50 border-amber-200 text-amber-800'
                              }`}
                            >
                              {w}
                            </span>
                          ))}
                        </div>
                      )}

                      <div className="flex items-center justify-end gap-2 pt-1">
                        <button
                          onClick={() => copyActionPlan(s)}
                          className="px-3 py-1 text-xs font-medium text-gray-700 border border-gray-300 rounded hover:bg-gray-50"
                        >
                          Copy as action plan
                        </button>
                        <button
                          onClick={() => markAccepted(s, idx)}
                          disabled={acceptingIdx === idx || accepted}
                          className={`px-3 py-1 text-xs font-medium rounded ${
                            accepted
                              ? 'bg-green-100 text-green-800 border border-green-300'
                              : 'text-white bg-pacific-600 hover:bg-pacific-700 disabled:opacity-50'
                          }`}
                        >
                          {accepted
                            ? 'Accepted — note appended'
                            : acceptingIdx === idx
                              ? 'Saving…'
                              : 'Mark this approach as accepted'}
                        </button>
                      </div>
                    </div>
                  );
                })
              ) : (
                <p className="text-sm text-gray-500 italic">
                  The model returned no suggestions. Try refining the ingredient name or demographic.
                </p>
              )}

              {error && <p className="text-xs text-red-600">{error}</p>}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
