/**
 * code-weave Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection.
 *
 * Mirrors apps/depth-chart/worker.ts. See docs/security/cf-headers-wrapper.md
 * for the full pattern + rollout doc.
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  HARBOUR_DEFAULT_CSP,
} from "@windedvertigo/security";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

export default wrapWithSecurityHeaders(openNextHandler, {
  csp: HARBOUR_DEFAULT_CSP,
  skipPaths: [/^\/cdn-cgi\//],
});
