"use client";

import { useState, useCallback } from "react";

type ExportMode = "pdf" | "print";

export function ChartExport({ mode }: { mode: ExportMode }) {
  const [exporting, setExporting] = useState(false);

  const exportFanChartPdf = useCallback(async () => {
    setExporting(true);
    try {
      // dynamically import to avoid SSR issues
      const { jsPDF } = await import("jspdf");
      await import("svg2pdf.js");

      // find the fan chart SVG in the DOM
      const svg = document.querySelector<SVGSVGElement>(
        "[data-chart='fan'] svg",
      );
      if (!svg) {
        console.error("fan chart svg not found");
        return;
      }

      // clone the SVG so we can modify it without affecting the DOM
      const clone = svg.cloneNode(true) as SVGSVGElement;
      const width = svg.clientWidth || 800;
      const height = svg.clientHeight || 500;

      // set explicit dimensions and namespace
      clone.setAttribute("width", String(width));
      clone.setAttribute("height", String(height));
      clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");

      // resolve CSS custom properties and classes to inline styles
      resolveStyles(clone);

      // create PDF in landscape, sized to fit the chart
      const pdfWidth = 420; // A3 width in mm
      const pdfHeight = 297; // A3 height in mm
      const doc = new jsPDF({
        orientation: "landscape",
        unit: "mm",
        format: "a3",
      });

      // add header
      doc.setFontSize(14);
      doc.setFont("helvetica", "normal");
      doc.text("family tree — fan chart", 15, 15);

      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      const today = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
      doc.text(today, 15, 22);
      doc.text("generated by w.v ancestry", 15, 27);

      // calculate scale to fit chart in remaining space
      const chartTop = 32; // mm from top after header
      const availableWidth = pdfWidth - 30; // 15mm margin each side
      const availableHeight = pdfHeight - chartTop - 10;

      const scaleX = availableWidth / width;
      const scaleY = availableHeight / height;
      const scale = Math.min(scaleX, scaleY);

      const chartWidth = width * scale;
      const chartHeight = height * scale;
      const offsetX = 15 + (availableWidth - chartWidth) / 2;

      // temporarily add clone to DOM for svg2pdf to process
      clone.style.position = "absolute";
      clone.style.left = "-9999px";
      document.body.appendChild(clone);

      try {
        await doc.svg(clone, {
          x: offsetX,
          y: chartTop,
          width: chartWidth,
          height: chartHeight,
        });
      } finally {
        document.body.removeChild(clone);
      }

      doc.save("family-tree-fan-chart.pdf");
    } catch (err) {
      console.error("pdf export failed:", err);
    } finally {
      setExporting(false);
    }
  }, []);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  if (mode === "pdf") {
    return (
      <button
        onClick={exportFanChartPdf}
        disabled={exporting}
        className="px-3 py-1.5 text-xs font-medium rounded-md transition-colors text-muted-foreground hover:text-foreground hover:bg-muted disabled:opacity-50"
        title="export fan chart as pdf"
      >
        {exporting ? "exporting..." : "export pdf"}
      </button>
    );
  }

  return (
    <button
      onClick={handlePrint}
      className="px-3 py-1.5 text-xs font-medium rounded-md transition-colors text-muted-foreground hover:text-foreground hover:bg-muted"
      title="print pedigree chart"
    >
      print
    </button>
  );
}

/**
 * resolve CSS custom properties and tailwind classes to inline styles
 * so the cloned SVG renders correctly in the PDF
 */
function resolveStyles(svg: SVGSVGElement) {
  const computed = getComputedStyle(document.documentElement);

  // resolve fill-foreground and fill-muted-foreground classes
  svg.querySelectorAll<SVGElement>(".fill-foreground").forEach((el) => {
    const color = computed.getPropertyValue("--color-foreground").trim();
    el.style.fill = color || "#000";
    el.classList.remove("fill-foreground");
  });

  svg.querySelectorAll<SVGElement>(".fill-muted-foreground").forEach((el) => {
    const color = computed.getPropertyValue("--color-muted-foreground").trim();
    el.style.fill = color || "#666";
    el.classList.remove("fill-muted-foreground");
  });

  // resolve any CSS custom property references in inline styles
  svg.querySelectorAll<SVGElement>("*").forEach((el) => {
    const fill = el.getAttribute("fill");
    if (fill?.startsWith("var(")) {
      const resolved = resolveCssVar(fill, computed);
      if (resolved) el.setAttribute("fill", resolved);
    }

    const stroke = el.getAttribute("stroke");
    if (stroke?.startsWith("var(")) {
      const resolved = resolveCssVar(stroke, computed);
      if (resolved) el.setAttribute("stroke", resolved);
    }

    // also check inline style properties
    if (el.style.fill?.includes("var(")) {
      el.style.fill = resolveCssVar(el.style.fill, computed) || el.style.fill;
    }
    if (el.style.stroke?.includes("var(")) {
      el.style.stroke =
        resolveCssVar(el.style.stroke, computed) || el.style.stroke;
    }
  });
}

function resolveCssVar(
  value: string,
  computed: CSSStyleDeclaration,
): string | null {
  const match = value.match(/var\(\s*(--[^,)]+)/);
  if (!match) return null;
  const resolved = computed.getPropertyValue(match[1]).trim();
  return resolved || null;
}
